apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: db
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
      name: redis
        
