apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: stophyeon/test:api-gw
          ports:
          - containerPort: 8888
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: apigw-config
            items:
              - key: application.yml
                path: application.yml