apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  application.yml: |
    server:
      port: 5080
    spring:
      cache:
        type: redis
      data:
        redis:
          host: redis-service.db.svc.cluster.local
          port: 6379
        mongodb:
          uri: mongodb://jjh:1234@mongodb-service.db.svc.cluster.local:27017/chat
          database: chat
      application:
        name: chat-api

    