apiVersion: v1
kind: ConfigMap
metadata:
  name: purchase-config
data:
  application.yml: |
    server:
      port: 6080
    spring:
      profiles:
        active: dev
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-payment-service.db.svc.cluster.local:3307/payment?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password : asas1212!
      application:
        name: purchase-api
      jpa:
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            show_sql: true
