apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
data:
  application.yml: |
    server:
      port: 8081
    spring:
      profiles:
        active: dev
      servlet:
        multipart:
          max-file-size: 128MB
          max-request-size: 128MB
          enabled: true
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-member-service.ptfd-db.svc.cluster.local:3308/member?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password : asas1212!
      application:
        name: member-api
      s3:
        accessKey: 38F622CB2CE7257CD472
        secretKey: 8AD3992D3D09C965081B0B4687B4D6B017E4D915
        bucket: contest16-objectstorage-imagebucket
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            show_sql: true
    management:
      endpoints:
        web:
          exposure:
            include: ['refresh','beans','env']
    jwt:
      secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK