apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config
data:
  application.yml: |
    server:
      port: 7080
    spring:
      profiles:
        active: dev
      main:
        allow-bean-definition-overriding: true
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-post-service.db.svc.cluster.local:3305/post?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password : asas1212!
      application:
        name: post-api
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            show_sql: true
      mail:
        host: smtp.naver.com
        port: 465
        username: 5-stars16
        password: asas1212!
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
          mail.smtps.checkserveridentity: true
          mail.smtps.ssl.trust: "*"
          mail.debug: false
          mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      s3:
        accessKey: 38F622CB2CE7257CD472
        secretKey: 8AD3992D3D09C965081B0B4687B4D6B017E4D915
        bucket: contest16-objectstorage-imagebucket
    management:
      endpoints:
        web:
          exposure:
            include: ['refresh','beans','env']
    jwt:
      secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK