apiVersion: v1
data:
  my.cnf: |
    [client]
    default-character-set = utf8mb4
    [mysql]
    default-character-set = utf8mb4
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    init_connect='SET NAMES utf8mb4'
    max_connect_errors = 5
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-07T06:05:23Z"
  name: mysql-client-config
  namespace: db
  resourceVersion: "11774685"
  uid: 4be226d8-34b1-421f-b653-a19f27cd994c
